PVCName: oauth-v1-pvc  
Namespace: oauth-v1
Storage: 30Gi

# StatefulSet
StatefulName: oauth-v1  
ReplicaCount: 3
ImageName: 599690875663.dkr.ecr.us-west-1.amazonaws.com/testoauth
ContainerPort: 80

#Tolerations
Tolerationskey: app
Operator: Equal
Tolerationsvalue: oauth
Effect: PreferNoSchedule
# Services
ServiceName: oauth-v1-service  # Updated key name
Port: 80
TargetPort: 80
Path: "/tmp"
ContainerPath: "/app"
